server:
  port: 80

spring:
    datasource:
        name: test
        url: jdbc:mysql://192.168.1.89:3306/parking?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
        username: root
        #此处密码待加密存放
        password: abc_123456
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false20+
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20

  #redis:
    # redis数据库索引（默认为0），我们使用索引为3的数据库，避免和其他数据库冲突
    #database: 3
    # redis服务器地址（默认为localhost）
    #host: localhost
    # redis端口（默认为6379）
    #port: 6379
    # redis访问密码（默认为空）
    #password:
    # redis连接超时时间（单位为毫秒）
    #timeout: 0
    # redis连接池配置
    #pool:
      # 最大可用连接数（默认为8，负数表示无限）
      #max-active: 8
      # 最大空闲连接数（默认为8，负数表示无限）
      #max-idle: 8
      # 最小空闲连接数（默认为0，该值只有为正数才有作用）
      #min-idle: 0
      # 从连接池中获取连接最大等待时间（默认为-1，单位为毫秒，负数表示无限）
      #max-wait: -1

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.drzk.mapper

pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql

    #log4j日志，异常